### ISSUE TITLE
Feature Request - LibreOffice slide generator

### ISSUE THREAD

**Issue by fightingtexasaggie** [franciscouzo/corporate_bullshit#2]
It would be really nice to have this callable in LibreOffice, to generate typical corporate presentations, complete with wiz-bang features and animations and bullet points. Similarly, a SCORM presentation that reads the slides aloud in the most annoying voice possible would be awesome.

**Comment by franciscouzo** [comment]
That's out of scope for this project, from a cursory look, it seems LibreOffice has a Python API, so you should be able to call this library from it.
